/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "votasanremo.h"

bool_t
xdr_Canzone (XDR *xdrs, Canzone *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cantante, 64))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->titolo, 64))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomeFile, 64))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voti))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Podio (XDR *xdrs, Podio *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->canzoni, LUNGHPOD,
		sizeof (Canzone), (xdrproc_t) xdr_Canzone))
		 return FALSE;
	return TRUE;
}
