/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTASANREMO_H_RPCGEN
#define _VOTASANREMO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define LUNGHPOD 3
#define NUMFILE 10

struct Canzone {
	char *cantante;
	char *titolo;
	char *nomeFile;
	int voti;
};
typedef struct Canzone Canzone;

struct Podio {
	Canzone canzoni[LUNGHPOD];
};
typedef struct Podio Podio;

#define VOTASANREMO 0x20000013
#define VOTASANREMOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_PODIO 1
extern  Podio * visualizza_podio_1(void *, CLIENT *);
extern  Podio * visualizza_podio_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(char **, CLIENT *);
extern  int * esprimi_voto_1_svc(char **, struct svc_req *);
extern int votasanremo_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_PODIO 1
extern  Podio * visualizza_podio_1();
extern  Podio * visualizza_podio_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int votasanremo_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Canzone (XDR *, Canzone*);
extern  bool_t xdr_Podio (XDR *, Podio*);

#else /* K&R C */
extern bool_t xdr_Canzone ();
extern bool_t xdr_Podio ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTASANREMO_H_RPCGEN */
