/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "conta.h"

bool_t
xdr_Result (XDR *xdrs, Result *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->caratteri))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->parole))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->linee))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->parolaspec))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->caratteri);
			IXDR_PUT_LONG(buf, objp->parole);
			IXDR_PUT_LONG(buf, objp->linee);
			IXDR_PUT_LONG(buf, objp->parolaspec);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->caratteri))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->parole))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->linee))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->parolaspec))
				 return FALSE;
		} else {
			objp->caratteri = IXDR_GET_LONG(buf);
			objp->parole = IXDR_GET_LONG(buf);
			objp->linee = IXDR_GET_LONG(buf);
			objp->parolaspec = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->caratteri))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parole))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->linee))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parolaspec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Contaocc (XDR *xdrs, Contaocc *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomeFile, 64))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->parola, 64))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Contafile (XDR *xdrs, Contafile *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->dir, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->pref, 64))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dim))
		 return FALSE;
	return TRUE;
}
