/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTA_H_RPCGEN
#define _CONTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Result {
	int caratteri;
	int parole;
	int linee;
	int parolaspec;
};
typedef struct Result Result;

struct Contaocc {
	char *nomeFile;
	char *parola;
};
typedef struct Contaocc Contaocc;

struct Contafile {
	char *dir;
	char *pref;
	int dim;
};
typedef struct Contafile Contafile;

#define CONTAPROG 0x20000013
#define CONTAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTAOCC 1
extern  Result * contaocc_1(Contaocc *, CLIENT *);
extern  Result * contaocc_1_svc(Contaocc *, struct svc_req *);
#define CONTAFILE 2
extern  int * contafile_1(Contafile *, CLIENT *);
extern  int * contafile_1_svc(Contafile *, struct svc_req *);
extern int contaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTAOCC 1
extern  Result * contaocc_1();
extern  Result * contaocc_1_svc();
#define CONTAFILE 2
extern  int * contafile_1();
extern  int * contafile_1_svc();
extern int contaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Result (XDR *, Result*);
extern  bool_t xdr_Contaocc (XDR *, Contaocc*);
extern  bool_t xdr_Contafile (XDR *, Contafile*);

#else /* K&R C */
extern bool_t xdr_Result ();
extern bool_t xdr_Contaocc ();
extern bool_t xdr_Contafile ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTA_H_RPCGEN */
